-- MySQL Script generated by MySQL Workbench
-- Wed Mar 11 20:56:29 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_student_resource_IS
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_student_resource_IS` ;

-- -----------------------------------------------------
-- Schema db_student_resource_IS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_student_resource_IS` DEFAULT CHARACTER SET utf8 ;
USE `db_student_resource_IS` ;

-- -----------------------------------------------------
-- Table `db_student_resource_IS`.`Roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_student_resource_IS`.`Roles` ;

CREATE TABLE IF NOT EXISTS `db_student_resource_IS`.`Roles` (
  `idRoles` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idRoles`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_student_resource_IS`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_student_resource_IS`.`User` ;

CREATE TABLE IF NOT EXISTS `db_student_resource_IS`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `middle_name` VARCHAR(45) NULL,
  `Roles_id` INT NOT NULL,
  `username` VARCHAR(45) NULL,
  `password` TEXT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `emailAddress_UNIQUE` (`email` ASC) ,
  INDEX `fk_Students_Roles1_idx` (`Roles_id` ASC) ,
  CONSTRAINT `fk_Students_Roles1`
    FOREIGN KEY (`Roles_id`)
    REFERENCES `db_student_resource_IS`.`Roles` (`idRoles`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_student_resource_IS`.`Files`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_student_resource_IS`.`Files` ;

CREATE TABLE IF NOT EXISTS `db_student_resource_IS`.`Files` (
  `idFile` INT NOT NULL AUTO_INCREMENT,
  `description` TINYTEXT NOT NULL,
  `source` TEXT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idFile`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_student_resource_IS`.`file_student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_student_resource_IS`.`file_student` ;

CREATE TABLE IF NOT EXISTS `db_student_resource_IS`.`file_student` (
  `student_id` INT NOT NULL,
  `file_id` INT NOT NULL,
  PRIMARY KEY (`student_id`, `file_id`),
  INDEX `fk_Student_has_File_File1_idx` (`file_id` ASC) ,
  INDEX `fk_Student_has_File_Student_idx` (`student_id` ASC) ,
  CONSTRAINT `fk_Student_has_File_Student`
    FOREIGN KEY (`student_id`)
    REFERENCES `db_student_resource_IS`.`User` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Student_has_File_File1`
    FOREIGN KEY (`file_id`)
    REFERENCES `db_student_resource_IS`.`Files` (`idFile`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_student_resource_IS`.`Grades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_student_resource_IS`.`Grades` ;

CREATE TABLE IF NOT EXISTS `db_student_resource_IS`.`Grades` (
  `idGrades` INT NOT NULL,
  PRIMARY KEY (`idGrades`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
